### PR TITLE
Release/18 nov 2022

### PR DESCRIPTION
**Pull request by codingki**
prod sync

### CODE REVIEW

**Review by joshuanatanielnm — APPROVED** [review]
Ship it 🚀

**Comment by joshuanatanielnm** [comment]
One concern that I have is the chart is not user friendly on mobile view, maybe can fix that in seperate PR

**Comment by codingki** [comment]
> One concern that I have is the chart is not user friendly on mobile view, maybe can fix that in seperate PR

Looks fine to me 
CleanShot 2022-11-18 at 06 52 10

**Comment by codingki** [comment]
Oh yea I see it, Yeah let's fix it on after release @joshuanatanielnm 
CleanShot 2022-11-18 at 06 54 19

**Pull request merged**
