### PR TITLE
Feat/chart loading and error state

### LINKED ISSUE #678: Chart Loading and Error state
Add loading and error state on Line chart:
- EthBtcPerfomanceCard.tsx
- UsdcPerfomanceCard.tsx
- PerfomanceCard.tsx

### PR DESCRIPTION
**Pull request by codingki**
Closes #678 

## Description

Implementing Loading and Error state for chart components

## Changes

- [x] [feat: add isError and rename fetching to isFetching](https://github.com/strangelove-ventures/sommelier/commit/c835bbad78aa38ed83de1e5c19e18ce562852c3e)
- [x] [feat: add ErrorCard component](https://github.com/strangelove-ventures/sommelier/commit/9036224a8f93e9935c7ea73a00db41e8db9a6852)
- [x] [feat: implement error and loading state](https://github.com/strangelove-ventures/sommelier/commit/10364cddced3fc9d093b8a70ceed9dd5b90375b4)

## Screenshots :

CleanShot 2022-11-29 at 03 04 52

### CODE REVIEW

**Review by joshuanatanielnm — APPROVED** [review]
LGTM 🚀

**Comment by joshuanatanielnm** [comment]
> LGTM 🚀

I think is not good to make the chart disappear whenever we update the chart limeline
image

**Comment by codingki** [comment]
> > LGTM 🚀
> 
> I think is not good to make the chart disappear whenever we update the chart limeline image

nice find and suggestion, it's actually because of urql `useQuery` refetch because `epoch` is changing fixed that on [feat: prevent urql useQuery refetch because epoch change](https://github.com/strangelove-ventures/sommelier/pull/695/commits/4f3c284190532d6d978f3f83711583722d5a0993)

**Review by joshuanatanielnm — APPROVED** [review]
LGTM 🚀

**Pull request merged**
