### PR TITLE
Feat/eth btc chart

### LINKED ISSUE #588: Cellar metrics update  2. iteration
For 2. iteration changes are pointed out in Red.
Figma-
https://www.figma.com/file/7IAQbLyzapnrow9sIcO77P/App?node-id=2195%3A101054

**Strategies page-**
Screenshot 2022-11-02 at 21 00 14

Lets add back " 1D Change" @joshuanatanielnm - 
Image

**Strategy landing pages-**
Screenshot 2022-11-02 at 21 01 02

Lets add back " 1D Change" and "Total Value" (same as TVM but litlebit different designg) @joshuanatanielnm 

Image

**Strategy details page-**
Screenshot 2022-11-02 at 21 02 18

Strategy details page TVM-

Image

Lets add back " 1D Change"  @joshuanatanielnm -
Image

**Tooltip text -** 

1M Change vs ETH/BTC 50/50  -    % change of token price compared to a benchmark portfolio of 50% ETH and 50% BTC

1D Change - % change of current token price vs. token price 1 day ago

### PR DESCRIPTION
**Pull request by codingki**
Closes #588 

## Description

This PR is for adding ETH BTC Chart/Strategy perfomance chart 

## Changes

- [x] [feat: add queries](https://github.com/strangelove-ventures/sommelier/commit/91f65ace2a539b919b4364d2e67ce1cc59e6c3b9)
- [x] [chore: add date-fns package](https://github.com/strangelove-ventures/sommelier/commit/e7717bb978443e7da8ef49f0c7f55792603ba932)
- [x] [refactor: chart helper utils function](https://github.com/strangelove-ventures/sommelier/commit/94585955f76874e24981cfac09edb781ae8b00d6)
- [x] [refactor: rename function and add option](https://github.com/strangelove-ventures/sommelier/commit/3e70f9fcaf73fefb07d7ff5ef8437141978d7792)
- [x] [chore: rename variable](https://github.com/strangelove-ventures/sommelier/commit/7b3e6960dc09aa94ef0ba156a74ac6fcf8f5e6fc)
- [x] [feat: remove asset symbol](https://github.com/strangelove-ventures/sommelier/commit/bad513a237b1f55847c31e348171b9d9f2810a0d)
- [x] [refactor: split fetch and calculation](https://github.com/strangelove-ventures/sommelier/commit/3e16ff2f66f8337157567717038900a26b48c845)
- [x] [feat: eth btc chart logic](https://github.com/strangelove-ventures/sommelier/commit/acabaf07bec4064a33bb9b90e609242d0ffc474d)
- [x] [feat: eth btc ui implementation](https://github.com/strangelove-ventures/sommelier/commit/973c474faffeff403c22b67e8015faba2af0efb4)

## Screenshots : 

CleanShot 2022-11-15 at 00 40 12
CleanShot 2022-11-15 at 00 40 49

### CODE REVIEW

**Comment by joshuanatanielnm** [comment]
Based on figma the chekbox can be unchecked
image

**Comment by codingki** [comment]
> Based on figma the chekbox can be unchecked image

Ah good catch, will add this after this PR

**Review by joshuanatanielnm — APPROVED** [review]
LGTM

**Review by xanderjl — APPROVED** [review]
Nothing immediately apparent that needs changes code-wise, but there's a bug in the chart's state:

image

image

No matter where I inspect on the graph, the token price is not updating, even though the trend value does. 🤔

**Review by xanderjl — CHANGES_REQUESTED** [review]
Crud. I meant to request changes. We need to find the state bug in that chart. Happy to pair if need be!

**Comment by codingki** [comment]
it's not a bug, it's expected from prod spec @xanderjl

**Comment by xanderjl** [comment]
Oh huh. Interesting. Feels awkward, but c'est la vie! LGTM then 😅

**Review by xanderjl — APPROVED** [review]

**Pull request merged**
