### PR TITLE
feat: add faq section to production

### LINKED ISSUE #526: FAQ under Cellars page
**Business case:**
We want to replace the "Education" section on the Cellars page (https://app.sommelier.finance/) with a FAQ section for a better user experience.

We want to use the same FAQ content as currently on the Marketing site.

**Todo:**
Replace the "Education" section on the Cellars page with FAQ section, using the design: https://www.figma.com/file/7IAQbLyzapnrow9sIcO77P/App?node-id=1631%3A44003

### PR DESCRIPTION
**Pull request by joshuanatanielnm**
Fixes #526 

## Description

Create FAQ section and replace Education section with FAQ, get FAQ data from marketing site 

## Changes

- [x] _**added new env variable on vercel to get data from sanity**_
- [x] create faq section
- [x] replace education with faq section 
- [x] configured sanity to get data from marketing site 
- [x] updated StrategyBreakdownCard tab border color

## Screenshots

image
image
image

## Links

Figma: https://www.figma.com/file/7IAQbLyzapnrow9sIcO77P/App?node-id=1631%3A44003

### CODE REVIEW

**Comment by xanderjl** [comment]
https://github.com/strangelove-ventures/cosmos-composer/pull/45#issuecomment-1282850918

It appears we have a mismatch between our cellar query and what's currently deployed?

**Comment by joshuanatanielnm** [comment]
hey @xanderjl is this what you mean by cellar query
```
export function useGetCellarQuery(options: Omit<Urql.UseQueryArgs<GetCellarQueryVariables>, 'query'>) {
  return Urql.useQuery<GetCellarQuery>({ query: GetCellarDocument, ...options });
};
```

**Comment by xanderjl** [comment]
@joshuanatanielnm This error is occurring at build time. Data the query is attempting to fetch is returning undefined. I assume in the `getStaticProps` function of that cellar route.

**Comment by joshuanatanielnm** [comment]
Oh, after I take a look, this branch is using different query with the staging. should I update this branch cellars query to follow staging? @xanderjl

**Comment by xanderjl** [comment]
@joshuanatanielnm You and @codingki should coordinate on what the proper query should be 🤝

**Comment by joshuanatanielnm** [comment]
Okay sure @xanderjl

**Review by codingki — APPROVED** [review]

**Comment by joshuanatanielnm** [comment]
Okay @codingki 👍

**Pull request merged**
