### PR TITLE
Feat&fix/ chart improvement

### PR DESCRIPTION
**Pull request by codingki**
Chart Improvement

## Description

- refactor `useDailyChange` from use daily data to previous 24h data
- line chart prevent duplicate data 
- line chart improve accuracy 
- filter line chart by clicking the "legends"
- fix 0 percentage not showing
- date formating

## Changes

List any technical changes.

- [x] [fix: 0 percentage not showing](https://github.com/strangelove-ventures/sommelier/commit/8d0fb7a188451898e2a57efeabd44afd961e8feb)
- [x] [fix: improve chart date accuracy](https://github.com/strangelove-ventures/sommelier/commit/6ebdd3e1cffd16d3a6f4ffc6c32b512d6ef38302)
- [x] [refactor(useDailyChange): use previous 24 hrs instead of 1 day](https://github.com/strangelove-ventures/sommelier/commit/7cef39c91126a5275b6b638feae3237516575d78)
- [x] [feat: filter legend chart clickable](https://github.com/strangelove-ventures/sommelier/commit/e4a21311f91cd3d30c2ed979def0a121878aeb36)
- [x] [fix: duplicate data key](https://github.com/strangelove-ventures/sommelier/commit/5fb5f62760551c0ed8c8a24c72b97df65b9e2c86)
- [x] [fix: prevent line race, update tokenPriceChange when clicked](https://github.com/strangelove-ventures/sommelier/commit/95ce03c38cb3b3208c130aa32a9d2b86eb6ad3c8)
- [x] [chore: improve readability](https://github.com/strangelove-ventures/sommelier/commit/126555e3068226521fed1af0d152b1b5ffb36ba3)
- [x] [feat: add first date and format date](https://github.com/strangelove-ventures/sommelier/commit/c02eddb33a465528f1de32d233247feea93fdb73)

## Screenshots:

https://user-images.githubusercontent.com/39829726/202289468-7657211d-2f3e-4b21-bf73-6a8d438f4624.mp4

### CODE REVIEW

**Comment by joshuanatanielnm** [comment]
Why show `%` while loading the data ?

image

**Comment by joshuanatanielnm** [comment]
I think we also need to remove this chart

image

**Comment by codingki** [comment]
> I think we also need to remove this chart
> 
> image

Will do it in different PR

**Comment by codingki** [comment]
> Why show `%` while loading the data ?
> 
> image

Will add the loading state for this

**Comment by codingki** [comment]
> If possible I think you can add this behaviour also
> 
> image

Need more time for dig in for this spec, I'll try to do when doing the popover thing(4th iteration cellar metrics #609)

**Comment by codingki** [comment]
empty state added @joshuanatanielnm

**Review by joshuanatanielnm — CHANGES_REQUESTED** [review]
Make the percentage loading consistent between each page

image
image
image

**Review by xanderjl — APPROVED** [review]
Code quality looks great! Agree with @joshuanatanielnm re: keeping the loading state consistent across pages. That could also be a separate PR, honestly.

**Review by joshuanatanielnm — APPROVED** [review]

**Pull request merged**
